import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Contact Card',
  description: 'Generated by Rpm Code',
  generator: "Next.js",
  image: "/favicon.png",
  authors: [
    { name: "Eiichi Matsuo" },
    { name: "RPM Code", url: "https://www.rpmspeedcode.com/" },
  ],
  creator: "Eiichi Matsuo",
  images: [
    {
      url: '/favicon.png',
      width: 200, 
      height: 200,
      alt: 'RPM Code | Contact Card',
    },
  ],
  openGraph: {
    images: "/favicon.png",
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
